### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by xmuplus** [gragrance/CaptuocrToy#13]
按照中文文本内容，一步步执行安装都没问题，到最后一步 `BuildArea/autobuild.sh` 报错。

![36092353-097d98ce-1022-11e8-960e-d83e2b64c080](https://user-images.githubusercontent.com/20852657/36092432-4cf5722a-1022-11e8-83ee-b1ec576e57b2.png)

**Comment by zeptolee** [comment]
看起来是重命名了

**Comment by xmuplus** [comment]
这该怎么处理呢？

**Comment by gragrance** [comment]
@xmuplus 
请尝试使用xCode打开一次Captuocr.xcworkspace，应该会自动生成这个scheme

**Comment by stoensin** [comment]
如果 xocde 已经卸载了呢 ,只安装了命令行的,那有什么解决方案不.除了重新安装 xcode
