### ISSUE TITLE
调的那些ocr接口，能提供一下吗

### ISSUE THREAD

**Issue by guotie** [gragrance/CaptuocrToy#6]
不想去源代码里找了

**Comment by gragrance** [comment]
使用 **[百度 OCR](https://cloud.baidu.com/doc/OCR/index.html)** 或者 **[GOOGLE CLOUD VISION](https://cloud.google.com/vision/?hl=zh_CN)** API

**Comment by gragrance** [comment]
前者有每天 500 条免费额度，后者每个月 1000 条免费额度

**Comment by guotie** [comment]
多谢！
