### ISSUE TITLE
Distribute through the Mac App Store

### ISSUE THREAD

**Issue by ddddxxx** [gragrance/CaptuocrToy#7]

**Comment by gragrance** [comment]
Sorry , I don't have an apple developer account

**Comment by ddddxxx** [comment]
I have a developer account and would like to upload this app (with your permission). What do you think?

**Comment by gragrance** [comment]
My intention of developing this software is to eliminate people's doubt of the difficulty of getting started with MAC development. The purpose has been achieved, and yes, you can do anything with it.  Please keep the github reference link in the release notes
